name: ci

on:
  pull_request:
    branches: [main]

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code 
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: install dependencies
        run: npm ci

      - name: run tests
        run: npm run test -- --coverage


  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code 
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: install dependencies
        run: npm ci

      - name: run style
        run: npm run format:check

      - name: run lint
        run: npm run lint